# Generated by Django 5.0.1 on 2024-02-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0004_alter_incidentdown_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidentdown',
            options={'managed': False, 'ordering': ('date',)},
        ),
    ]
