# Generated by Django 5.0.1 on 2024-02-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0005_alter_incidentdown_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incidentdown',
            table='[dbo.SNMaintenanceForm]',
        ),
    ]
