# Generated by Django 3.2.23 on 2024-02-01 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0006_alter_incidentdown_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incidentdown',
            table=None,
        ),
    ]
