# Generated by Django 3.2.23 on 2024-02-01 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0008_alter_incidentdown_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='incidentdown',
            table='SNDownForm',
        ),
    ]
