# Generated by Django 3.2.23 on 2024-02-02 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0009_alter_incidentdown_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentdown',
            name='process',
            field=models.BooleanField(default=False),
        ),
    ]
