# Generated by Django 3.2.23 on 2024-02-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0010_incidentdown_process'),
    ]

    operations = [
        migrations.CreateModel(
            name='SnowIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, db_column='emailAddress', max_length=200, null=True)),
                ('description', models.TextField(blank=True, db_column='description', null=True)),
                ('impact', models.IntegerField(default=4)),
                ('urgency', models.IntegerField(default=4)),
                ('worknotes', models.TextField(blank=True, null=True)),
                ('assignment_group', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.IntegerField(default=1)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('process', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'SnowIncidentForm',
                'ordering': ('date',),
            },
        ),
    ]
