# Generated by Django 3.2.23 on 2024-02-04 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidentdown', '0011_snowincident'),
    ]

    operations = [
        migrations.AddField(
            model_name='snowincident',
            name='comments',
            field=models.TextField(blank=True, db_column='comments', null=True),
        ),
        migrations.AlterField(
            model_name='snowincident',
            name='name',
            field=models.CharField(blank=True, db_column='caller_id', max_length=200, null=True),
        ),
    ]
